-- Ensure data_collection_jobs table exists with correct schema
create table if not exists public.data_collection_jobs (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    area_name text not null,
    status text default 'processing',
    collected_count integer default 0,
    completed_at timestamp with time zone
);

-- Ensure RLS is enabled
alter table public.data_collection_jobs enable row level security;

-- Simple policy for authenticated users (admins)
create policy "Enable all access for authenticated users"
on public.data_collection_jobs
for all
to authenticated
using (true)
with check (true);

-- Ensure candidate_restaurants table has all needed columns
alter table public.candidate_restaurants
add column if not exists reliability_score integer default 0,
add column if not exists sources jsonb[] default array[]::jsonb[];
